### ISSUE TITLE
Is it possible to make video to video?

### ISSUE THREAD

**Issue by cheezecrisp** [HelloVision/ComfyUI_HelloMeme#19]
Copy the face expression and voice lip shape from Video A to Video B

**Comment by songkey** [comment]
The current solution does not take video-to-video application scenarios into account. If forced to apply it, uncontrollable mismatches may appear in blending areas such as hair edges, facial edges, or neck edges.

At this stage, we are still focusing on optimizing facial expressiveness, style compatibility, and inter-frame continuity. Once these are addressed, we may develop a customized version specifically for video-to-video scenarios.

**Comment by cheezecrisp** [comment]
> The current solution does not take video-to-video application scenarios into account. If forced to apply it, uncontrollable mismatches may appear in blending areas such as hair edges, facial edges, or neck edges.
> 
> At this stage, we are still focusing on optimizing facial expressiveness, style compatibility, and inter-frame continuity. Once these are addressed, we may develop a customized version specifically for video-to-video scenarios.

Got it. Thank you.
