### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ricardo-ml** [HelloVision/ComfyUI_HelloMeme#23]
python 3.10
torch 2.5.1
cuda 12.4

![1](https://github.com/user-attachments/assets/cbc43b9b-8549-4c5c-931c-330ae277b011)
![2](https://github.com/user-attachments/assets/69b27512-2d7d-41f1-9d4a-9be03afa549f)

I used the pictures and videos in the example for testing, and the above error occurred. What is the problem?

**Comment by songkey** [comment]
Based on the error log, this issue seems to be caused by the driving video being too short, as I didn’t account for cases where the driving video is shorter than 30 frames. Thank you for your feedback; I will test and optimize to address this bug.

**Comment by ricardo-ml** [comment]
@songkey I found the reason. It was because I accidentally set frame_load_cap=1. now it's work. thank you so mush
